# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac684b00f3045eecc1588f0de46ad41e6ebea484710885cdce72105eff959d59ae16afaac5bf814264c27dee4d03d755a3d42da1743bc23ad21317c21083fc3

test:
  secret_key_base: 033eda7078a619a794f7db34bcaaa9c66a41ee36d9fd024e7c0c7dee57b59679d4115ea28a8b1346404e9e95b9379ef04bd5b520b35f61350b9929f40ba08ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
